export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>This is the header of the website</h1>
        </header>

        {children}

        <footer>
          <h2>This is the footer of the website</h2>
          <h1>This applies to all the pages across navigation</h1>
        </footer>
      </body>
    </html>
  );
}
